mysite/analistarh/urls.py
from django.urls import path
from . import views

app_name = "analistarh"

"""Configurando as urls para a página de login"""
urlpatterns = [
    path("", views.index, name="index"),
    path("analistarh", views.procurar_analista, name="analistarh"),
    path("analistarh/info", views.editar_analista, name="analistarh_info"),
    path("professor", views.procurar_professor, name="professor"),
    path("professor/info", views.editar_professor, name="professor_info"),
    path("secretario", views.procurar_secretario, name="secretario"),
    path("secretario/info", views.editar_secretario, name="secretario_info"),


    path("analistarh/info/salvar", views.analistarh_salvar, name="analistarh_salvar"),
    path("professor/info/salvar", views.professor_salvar, name="professor_salvar"),
    path("secretario/info/salvar", views.secretario_salvar, name="secretario_salvar"),

    path("analistarh/info/apagar", views.analistarh_apagar, name="analistarh_apagar"),
    path("professor/info/apagar", views.professor_apagar, name="professor_apagar"),
    path("secretario/info/apagar", views.secretario_apagar, name="secretario_apagar"),
]

mysite/login/urls.py
from django.urls import path
from . import views

app_name = "login"

"""Configurando as urls para a página de login"""
urlpatterns = [
    path("", views.index, name="index"),
    path("connect", views.connect, name="connect"), #"^(?P<id>[\w-]+)/$"
    path("mudar_senha", views.index_mudar_senha, name="mudar_senha_pag"),
    path("mudar_senha/mudar", views.mudar_senha, name="mudar"),
    path("sair", views.sair, name="sair")
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from dotenv import load_dotenv
import os

# Setando as minhas próprias variáveis de ambiente
load_dotenv()
print(os.environ["API_URL"])

urlpatterns = [
    path("", include("root.urls")),
    path("admin/", admin.site.urls),
    path("login/", include("login.urls")),
    path("erros/", include("errors.urls")),
    path("analistarh/", include("analistarh.urls")),
    path("secretario/", include("secretario.urls")),
    path("professor/", include("professor.urls")),
    path("aluno/", include("aluno.urls"))
]

mysite/root/urls.py
from django.urls import path
from . import views

app_name = "root"

"""Configurando as urls para a página root"""
urlpatterns = [
    path("", views.index, name="index")
]

mysite/api_integration/models/analistarh.py
from typing import Any
from . pessoa import Pessoa

class AnalistaRH(Pessoa):
    """Model para a entidade AnalistaRH, herda Pessoa."""
    def __call__(self, *args: Any, **kwds: Any) -> Any:
        return super().__call__(*args, **kwds)
    

mysite/analistarh/views.py
import os, json
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpRequest
from api_integration import api, utils
from login.views import is_logged, set_cookies

conn = api.Connection(os.environ["API_URL"])

def check_login(request: HttpRequest) -> [dict, api.Login]:
    # Verificando se o usuário está logado.
    logged, login = is_logged(request)
    if not logged:
        return redirect("login:index"), login

    # Fazendo o request na API
    response, analistarh = conn.consultar.analistarh(login.token, login.id)
    context = {
        "erros":[]
    }
    print("area status code:", response.status_code)

    # Caso o token esteja expirado.
    if response.status_code == 401:
        # Verificando se o refresh_token é válido
        refresh = conn.refresh(login.id, login.token, login.refresh_token)
        if refresh.status_code == 400:
            return redirect("login:index"), login
        
        # Caso o refresh tenha tido êxito
        login = api.Login()
        login.set_values_with_response(refresh)
        # Fazendo o request na API novamente com o novo token
        response, analistarh = conn.consultar.analistarh(login.token, login.id)

    # Caso o token seja válido, mas o usuário não tenha permissão para usar o endpoint.
    elif response.status_code == 403 or login.cargo != utils.Cargo.ANALISTARH:
        return redirect("erros:403"), login
    
    # Caso tudo ocorra bem
    context["analistarh"] = analistarh
    return context, login

# Create your views here.
def index(request: HttpRequest):
    """Página inicial da área do Analista de RH"""
    context, login = check_login(request)
    if not isinstance(context, dict):
        return context

    # Adicionando o obj ao contexto e respondendo o request.
    return set_cookies(render(request, "analistarh/index.html", context), login)

def procurar_analista(request: HttpRequest):
    """Página inicial para buscas de Analista de RH"""
    context, login = check_login(request)
    if not isinstance(context, dict):
        return context
    
    filtro = request.GET.get("filtro", "")
    response, analistasrh = conn.procurar.analistarh(login.token, filtro)
    context["resultados"] = analistasrh
    
    # Adicionando o obj ao contexto e respondendo o request.
    return set_cookies(render(request, "analistarh/manter_analista.html", context), login)

def procurar_secretario(request: HttpRequest):
    """Página inicial para buscas de secretario"""
    context, login = check_login(request)
    if not isinstance(context, dict):
        return context
    
    filtro = request.GET.get("filtro", "")
    response, secretarios = conn.procurar.secretario(login.token, filtro)
    context["resultados"] = secretarios
    
    # Adicionando o obj ao contexto e respondendo o request.
    return set_cookies(render(request, "analistarh/manter_secretario.html", context), login)

def procurar_professor(request: HttpRequest):
    """Página inicial para buscas de professor"""
    context, login = check_login(request)
    if not isinstance(context, dict):
        return context
    
    filtro = request.GET.get("filtro", "")
    response, professores = conn.procurar.professor(login.token, filtro)
    context["resultados"] = professores
    
    # Adicionando o obj ao contexto e respondendo o request.
    return set_cookies(render(request, "analistarh/manter_professor.html", context), login)

def editar_analista(request: HttpRequest):
    """Página para cadastro ou alteração de cadastro de AnalistaRH"""
    context, login = check_login(request)
    if not isinstance(context, dict):
        return context
    
    id = request.GET.get("id", "")
    if id != "":
        response, analistarh = conn.consultar.analistarh(login.token, id)
        context["cadastro"] = analistarh
    else:
        context["cadastro"] = None

    # Adicionando o obj ao contexto e respondendo o request.
    return set_cookies(render(request, "analistarh/info_analista.html", context), login)

def editar_professor(request: HttpRequest):
    """Página para cadastro ou alteração de cadastro de professor"""
    context, login = check_login(request)
    if not isinstance(context, dict):
        return context
    
    id = request.GET.get("id", "")
    if id != "":
        response, professor = conn.consultar.professor(login.token, id)
        context["cadastro"] = professor
    else:
        context["cadastro"] = None

    # Adicionando o obj ao contexto e respondendo o request.
    return set_cookies(render(request, "analistarh/info_professor.html", context), login)

def editar_secretario(request: HttpRequest):
    """Página para cadastro ou alteração de cadastro de secretario"""
    context, login = check_login(request)
    if not isinstance(context, dict):
        return context
    
    id = request.GET.get("id", "")
    if id != "":
        response, secretario = conn.consultar.secretario(login.token, id)
        context["cadastro"] = secretario
    else:
        context["cadastro"] = None

    # Adicionando o obj ao contexto e respondendo o request.
    return set_cookies(render(request, "analistarh/info_secretario.html", context), login)

def analistarh_salvar(request: HttpRequest):
    context, login = check_login(request)
    if not isinstance(context, dict):
        return context

    id = request.GET.get("id", "")
    context["status"] = {"200_delete":False, "delete_error":False, "200":False, "400":False, "409":False, "500":False, "418": False}

    obj = api.AnalistaRH(
        nome = request.GET.get("nome", ""),
        rg = int(request.GET.get("rg", "")),
        cpf = int(request.GET.get("cpf", "")),
        telefone = int(request.GET.get("telefone", "")),
        email = request.GET.get("email", "")
    )

    if id == "":
        response = conn.cadastrar.analistarh(login.token, obj)
    else:
        response = conn.editar.analistarh(login.token, id, obj)
 
    if response.status_code == 200:
        context["status"]["200"] = True
    if response.status_code == 400:
        context["status"]["400"] = True
    if response.status_code == 409:
        context["status"]["409"] = True
    if response.status_code == 500:
        context["status"]["500"] = True
    return set_cookies(render(request, "analistarh/info_analista.html", context), login)

def secretario_salvar(request: HttpRequest):
    context, login = check_login(request)
    if not isinstance(context, dict):
        return context

    id = request.GET.get("id", "")
    context["status"] = {"200_delete":False, "delete_error":False, "200":False, "400":False, "409":False, "500":False, "418": False}

    obj = api.Secretario(
        nome = request.GET.get("nome", ""),
        rg = int(request.GET.get("rg", "")),
        cpf = int(request.GET.get("cpf", "")),
        telefone = int(request.GET.get("telefone", "")),
        email = request.GET.get("email", "")
    )

    if id == "":
        response = conn.cadastrar.secretario(login.token, obj)
    else:
        response = conn.editar.secretario(login.token, id, obj)
 
    if response.status_code == 200:
        context["status"]["200"] = True
    if response.status_code == 400:
        context["status"]["400"] = True
    if response.status_code == 409:
        context["status"]["409"] = True
    if response.status_code == 500:
        context["status"]["500"] = True
    return set_cookies(render(request, "analistarh/info_secretario.html", context), login)

def professor_salvar(request: HttpRequest):
    context, login = check_login(request)
    if not isinstance(context, dict):
        return context

    id = request.GET.get("id", "")
    context["status"] = {"200_delete":False, "delete_error":False, "200":False, "400":False, "409":False, "500":False, "418": False}

    obj = api.Professor(
        nome = request.GET.get("nome", ""),
        rg = int(request.GET.get("rg", "")),
        cpf = int(request.GET.get("cpf", "")),
        telefone = int(request.GET.get("telefone", "")),
        email = request.GET.get("email", "")
    )

    if id == "":
        response = conn.cadastrar.professor(login.token, obj)
    else:
        response = conn.editar.professor(login.token, id, obj)
 
    if response.status_code == 200:
        context["status"]["200"] = True
    if response.status_code == 400:
        context["status"]["400"] = True
    if response.status_code == 409:
        context["status"]["409"] = True
    if response.status_code == 500:
        context["status"]["500"] = True
    return set_cookies(render(request, "analistarh/info_professor.html", context), login)

def analistarh_apagar(request: HttpRequest):
    context, login = check_login(request)
    if not isinstance(context, dict):
        return context

    id = request.GET.get("id", "")
    context["status"] = {"200_delete":False, "delete_error":False, "200":False, "400":False, "409":False, "500":False, "418": False}

    response = conn.apagar.analistarh(login.token, id)

    if response.status_code == 200:
        context["status"]["200_delete"] = True
    else:
        context["status"]["delete_error"] = True
    return set_cookies(render(request, "analistarh/info_analista.html", context), login)

def secretario_apagar(request: HttpRequest):
    context, login = check_login(request)
    if not isinstance(context, dict):
        return context

    id = request.GET.get("id", "")
    context["status"] = {"200_delete":False, "delete_error":False, "200":False, "400":False, "409":False, "500":False, "418": False}

    response = conn.apagar.secretario(login.token, id)

    if response.status_code == 200:
        context["status"]["200_delete"] = True
    else:
        context["status"]["delete_error"] = True
    return set_cookies(render(request, "analistarh/info_secretario.html", context), login)

def professor_apagar(request: HttpRequest):
    context, login = check_login(request)
    if not isinstance(context, dict):
        return context

mysite/login/templates/analistarh/index.html
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Área do Analista de RH</title>
    {% load static %}
    <link rel="shortcut icon" href="{% static 'icons/favicon.png'%}" type="image/x-icon">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/area.css'%}">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/area_header.css'%}">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/area_main.css'%}">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/area_footer.css'%}">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/area_do_analistarh.css'%}">
</head>
<body>
    <!-- Header, o cabeçalho da página -->
    <header>
        <!-- Ícone do sistema-->
        <div id="header-favicon">
            <img src="{% static 'icons/favicon.png'%}" alt="Íone da Universidade">
        </div>

        <!-- Título (h1) da página -->
        <div id="header-title">
            <h1>Área do Analista de RH</h1>
            <p>Olá, {{ analistarh.nome }}!</p>
        </div>

        <!-- Botões do cabeçalho-->
        <div id="header-buttons">
            <!-- Botão sair (link para a rota no Back End) -->
            <div id="sair-button">
                <a href="{% url 'login:sair' %}">Sair</a>
            </div>
            
            <!-- Botão trocar de senha (link para a rota no Back End) -->
            <div id="trocar-de-senha-button">
                <a href="{% url 'login:mudar_senha_pag' %}">Trocar de Senha</a>
            </div>
        </div>

        <div class="clear"></div>
    </header>

    <!-- Main, onde fica todo o conteúdo principal da página -->
    <main>
        <section> <!-- Coloque o conteúdo dentro desta seção, pois ela é centralizada -->
            <div class="container"> 
                <div class="option-item">
                    <a href="{% url 'analistarh:professor'  %}">
                        <div class="option-item-icon">
                            <img src="{% static 'icons/manter_usuario.png'%}" alt="">
                        </div>
                        <h2>Professores</h2>
                    </a>
                </div>
                <div class="option-item">
                    <a href="{% url 'analistarh:secretario'  %}">
                        <div class="option-item-icon">
                            <img src="{% static 'icons/manter_usuario.png'%}" alt="">
                        </div>
                        <h2>Secretários</h2>
                    </a>
                </div>
                <div class="option-item">
                    <a href="{% url 'analistarh:analistarh'  %}">
                        <div class="option-item-icon">
                            <img src="{% static 'icons/manter_usuario.png'%}" alt="">
                        </div>
                        <h2>Analistas de RH</h2>
                    </a>
                </div>
        </section>
    </main>

    <!-- Footer, o rodapé da página -->
    <footer>
        <!-- Primeira seção do rodapé -->
        <section id="footer-section-1">
            <h2>Sobre</h2>
            <p>PIM do 4° Semestre</p>
            <p>Grupo: DS4.4</p>
        </section>

        <!-- Segunda seção do rodapé -->
        <section id="footer-section-2">
            <h2>Atribuições</h2>
            <p><a href="https://www.flaticon.com/br/icones-gratis/universidade" class="link" target="_blank">Favicon by Flaticon</a></p>
            <p><a href="https://www.freepik.com" class="link" target="_blank">Icons by Freepik</a></p>
        </section>
    </footer>
</body>
</html>

mysite/login/templates/analistarh/info_analista.html
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Área do Analista de RH</title>
    {% load static %}
    <link rel="shortcut icon" href="{% static 'icons/favicon.png'%}" type="image/x-icon">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/area.css'%}">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/area_header.css'%}">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/area_main.css'%}">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/area_footer.css'%}">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/info.css'%}">
    {% load static %}
    <script src="{% static 'js/manter.js' %}"></script>
</head>
<body>
    <!-- Header, o cabeçalho da página -->
    <header>
        <!-- Ícone do sistema-->
        <div id="header-favicon">
            <img src="{% static 'icons/favicon.png' %}" alt="Íone da Universidade">
        </div>

        <!-- Título (h1) da página -->
        <div id="header-title">
            <h1>
                <a href="{% url 'analistarh:index'%}">Área do Analista de RH</a>
                <span class="subtitle"> / AnalistaRH</span>
            </h1>
            <p>Olá, {{analistarh.nome}}!</p>
        </div>

        <!-- Botões do cabeçalho-->
        <div id="header-buttons">
            <!-- Botão sair (link para a rota no Back End) -->
            <div id="sair-button">
                <a href="{% url 'login:sair' %}">Sair</a>
            </div>
            
            <!-- Botão trocar de senha (link para a rota no Back End) -->
            <div id="trocar-de-senha-button">
                <a href="{% url 'login:mudar_senha_pag' %}">Trocar de Senha</a>
            </div>
        </div>

        <div class="clear"></div>
    </header>

    <!-- Main, onde fica todo o conteúdo principal da página -->
    <main>
        <section> <!-- Coloque o conteúdo dentro desta seção, pois ela é centralizada -->
            <div class="container"> 
                <div id="retornos">
                    {% if status.200 %} <div class="block-success">Cadastro/Alteração realizado(a) com sucesso.</div> {% endif %}
                    {% if status.200_delete %} <div class="block-success">Cadastro apagado com sucesso.</div> {% endif %}
                    {% if status.delete_error %} <div class="block-erro">Erro ao apagar cadastro.</div> {% endif %}
                    {% if status.400 %} <div class="block-erro">Um ou mais dados inseridos são inválidos.</div> {% endif %}
                    {% if status.409 %} <div class="block-erro">Um ou mais dados já pertecem a outro cadastro.</div> {% endif %}
                    {% if status.418 %} <div class="block-erro">Este cadastro não pode ser deletado pois está relacionado à outros.</div> {% endif %}
                    {% if status.500 %} <div class="block-erro">Ocorreu um erro com o servidor.</div> {% endif %}
                </div>
                <form action="{% url 'analistarh:analistarh_salvar'  %}" method="get">

                    <div>
                        {% if cadastro != None %}
                        <button type="button" onclick="redirect_to_cad(`{% url 'analistarh:analistarh_apagar' %}`,
                        `{{ cadastro.id }}`)">
                            <img src="{% static 'icons/apagar.png' %}" alt="">
                            <span>Apagar</span>
                        </button>
                        <input type="text" name="id" id="id" value="{{ cadastro.id }}" style="display: none;">
                        {% endif %}
                        <button type="submit">
                            <img src="{% static 'icons/novo.png' %}" alt="">
                            <span>Salvar</span>
                        </button>
                        <div style="clear: both;"></div>
                    </div>
            
                    <div class="form-input">
                        <input class="input" type="text" name="nome" id="nome" placeholder="Insira o valor aqui" required
                        {% if cadastro != None %} value="{{ cadastro.nome }}" {% endif %}>
                        <label for="nome">Nome</label>
                    </div>
                    <div class="form-input">
                        <input class="input" type="number" name="rg" id="rg" placeholder="Insira o valor aqui" required
                        {% if cadastro != None %} value="{{ cadastro.rg }}" {% endif %}>
                        <label for="rg">RG</label>
                    </div>
            
                    <div class="form-input">
                        <input class="input" type="number" name="cpf" id="cpf" placeholder="Insira o valor aqui" required
                        {% if cadastro != None %} value="{{ cadastro.cpf }}" {% endif %}>
                        <label for="cpf">CPF</label>
                    </div>
            
                    <div class="form-input">
                        <input class="input" type="number" name="telefone" id="telefone" placeholder="Insira o valor aqui" required
                        {% if cadastro != None %} value="{{ cadastro.telefone }}" {% endif %}>
                        <label for="telefone">Telefone</label>
                    </div>
                    <div class="form-input">
                        <input class="input" type="text" name="email" id="email" placeholder="Insira o valor aqui" required
                        {% if cadastro != None %} value="{{ cadastro.email }}" {% endif %}>
                        <label for="E-mail">E-mail</label>
                    </div>
                    <div style="clear: both;"></div>
                </form>
        </section>
    </main>

    <!-- Footer, o rodapé da página -->
    <footer>
        <!-- Primeira seção do rodapé -->
        <section id="footer-section-1">
            <h2>Sobre</h2>
            <p>PIM do 4° Semestre</p>
            <p>Grupo: DS4.4</p>
        </section>

        <!-- Segunda seção do rodapé -->
        <section id="footer-section-2">
            <h2>Atribuições</h2>
            <p><a href="https://www.flaticon.com/br/icones-gratis/universidade" class="link" target="_blank">Favicon by Flaticon</a></p>
            <p><a href="https://www.freepik.com" class="link" target="_blank">Icons by Freepik</a></p>
        </section>
    </footer>
</body>
</html>

mysite/login/templates/analistarh/info_professor.html
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Área do Analista de RH</title>
    {% load static %}
    <link rel="shortcut icon" href="{% static 'icons/favicon.png'%}" type="image/x-icon">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/area.css'%}">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/area_header.css'%}">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/area_main.css'%}">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/area_footer.css'%}">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/info.css'%}">
    {% load static %}
    <script src="{% static 'js/manter.js' %}"></script>
</head>
<body>
    <!-- Header, o cabeçalho da página -->
    <header>
        <!-- Ícone do sistema-->
        <div id="header-favicon">
            <img src="{% static 'icons/favicon.png' %}" alt="Íone da Universidade">
        </div>

        <!-- Título (h1) da página -->
        <div id="header-title">
            <h1>
                <a href="{% url 'analistarh:index'%}">Área do Analista de RH</a>
                <span class="subtitle"> / Professor</span>
            </h1>
            <p>Olá, {{analistarh.nome}}!</p>
        </div>

        <!-- Botões do cabeçalho-->
        <div id="header-buttons">
            <!-- Botão sair (link para a rota no Back End) -->
            <div id="sair-button">
                <a href="{% url 'login:sair' %}">Sair</a>
            </div>
            
            <!-- Botão trocar de senha (link para a rota no Back End) -->
            <div id="trocar-de-senha-button">
                <a href="{% url 'login:mudar_senha_pag' %}">Trocar de Senha</a>
            </div>
        </div>

        <div class="clear"></div>
    </header>

    <!-- Main, onde fica todo o conteúdo principal da página -->
    <main>
        <section> <!-- Coloque o conteúdo dentro desta seção, pois ela é centralizada -->
            <div class="container"> 
                <div id="retornos">
                    {% if status.200 %} <div class="block-success">Cadastro/Alteração realizado(a) com sucesso.</div> {% endif %}
                    {% if status.200_delete %} <div class="block-success">Cadastro apagado com sucesso.</div> {% endif %}
                    {% if status.delete_error %} <div class="block-erro">Erro ao apagar cadastro.</div> {% endif %}
                    {% if status.400 %} <div class="block-erro">Um ou mais dados inseridos são inválidos.</div> {% endif %}
                    {% if status.409 %} <div class="block-erro">Um ou mais dados já pertecem a outro cadastro.</div> {% endif %}
                    {% if status.418 %} <div class="block-erro">Este cadastro não pode ser deletado pois está relacionado à outros.</div> {% endif %}
                    {% if status.500 %} <div class="block-erro">Ocorreu um erro com o servidor.</div> {% endif %}
                </div>
                <form action="{% url 'analistarh:professor_salvar'  %}" method="get">

                    <div>
                        {% if cadastro != None %}
                        <button type="button" onclick="redirect_to_cad(`{% url 'analistarh:professor_apagar' %}`,
                        `{{ cadastro.id }}`)">
                            <img src="{% static 'icons/apagar.png' %}" alt="">
                            <span>Apagar</span>
                        </button>
                        <input type="text" name="id" id="id" value="{{ cadastro.id }}" style="display: none;">
                        {% endif %}
                        <button type="submit">
                            <img src="{% static 'icons/novo.png' %}" alt="">
                            <span>Salvar</span>
                        </button>
                        <div style="clear: both;"></div>
                    </div>
            
                    <div class="form-input">
                        <input class="input" type="text" name="nome" id="nome" placeholder="Insira o valor aqui" required
                        {% if cadastro != None %} value="{{ cadastro.nome }}" {% endif %}>
                        <label for="nome">Nome</label>
                    </div>
                    <div class="form-input">
                        <input class="input" type="number" name="rg" id="rg" placeholder="Insira o valor aqui" required
                        {% if cadastro != None %} value="{{ cadastro.rg }}" {% endif %}>
                        <label for="rg">RG</label>
                    </div>
            
                    <div class="form-input">
                        <input class="input" type="number" name="cpf" id="cpf" placeholder="Insira o valor aqui" required
                        {% if cadastro != None %} value="{{ cadastro.cpf }}" {% endif %}>
                        <label for="cpf">CPF</label>
                    </div>
            
                    <div class="form-input">
                        <input class="input" type="number" name="telefone" id="telefone" placeholder="Insira o valor aqui" required
                        {% if cadastro != None %} value="{{ cadastro.telefone }}" {% endif %}>
                        <label for="telefone">Telefone</label>
                    </div>
                    <div class="form-input">
                        <input class="input" type="text" name="email" id="email" placeholder="Insira o valor aqui" required
                        {% if cadastro != None %} value="{{ cadastro.email }}" {% endif %}>
                        <label for="E-mail">E-mail</label>
                    </div>
                    <div style="clear: both;"></div>
                </form>
        </section>
    </main>

    <!-- Footer, o rodapé da página -->
    <footer>
        <!-- Primeira seção do rodapé -->
        <section id="footer-section-1">
            <h2>Sobre</h2>
            <p>PIM do 4° Semestre</p>
            <p>Grupo: DS4.4</p>
        </section>

        <!-- Segunda seção do rodapé -->
        <section id="footer-section-2">
            <h2>Atribuições</h2>
            <p><a href="https://www.flaticon.com/br/icones-gratis/universidade" class="link" target="_blank">Favicon by Flaticon</a></p>
            <p><a href="https://www.freepik.com" class="link" target="_blank">Icons by Freepik</a></p>
        </section>
    </footer>
</body>
</html>