mysite/login/urls.py
from django.urls import path
from . import views

app_name = "login"

"""Configurando as urls para a página de login"""
urlpatterns = [
    path("", views.index, name="index"),
    path("connect", views.connect, name="connect"), #"^(?P<id>[\w-]+)/$"
    path("mudar_senha", views.index_mudar_senha, name="mudar_senha_pag"),
    path("mudar_senha/mudar", views.mudar_senha, name="mudar"),
    path("sair", views.sair, name="sair")
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from dotenv import load_dotenv
import os

# Setando as minhas próprias variáveis de ambiente
load_dotenv()
print(os.environ["API_URL"])

urlpatterns = [
    path("", include("root.urls")),
    path("admin/", admin.site.urls),
    path("login/", include("login.urls")),
    path("erros/", include("errors.urls")),
    path("analistarh/", include("analistarh.urls")),
    path("secretario/", include("secretario.urls")),
    path("professor/", include("professor.urls")),
    path("aluno/", include("aluno.urls"))
]

mysite/professor/urls.py
from django.urls import path
from . import views

app_name = "professor"

"""Configurando as urls para a página de login"""
urlpatterns = [
    path("", views.index, name="index"),
    path("conteudo", views.procurar_conteudo, name="conteudo"),
    path("conteudo/listar", views.acessar_conteudos, name="acessar_conteudos"),
    path("disciplinas", views.acessar_disciplinas, name="disciplinas"),
    path("disciplinas/alunos", views.acessar_alunos_em_disciplinas, name="alunos_em_disciplinas"),
    path("mapa_de_notas", views.mapa_de_notas, name="mapa_de_notas"),

    
    path("conteudo/listar/download", views.download_conteudo, name="download_conteudo"),
    path("conteudo/listar/info", views.editar_conteudo, name="info_conteudo"),
    path("conteudo/listar/info/salvar", views.conteudo_salvar, name="conteudo_salvar"),
    path("conteudo/listar/info/apagar", views.conteudo_apagar, name="conteudo_apagar"),
    path("disciplinas/alunos/info", views.info_alunos_em_disciplinas, name="info_alunos_em_disciplinas"),
    path("disciplinas/alunos/info/salvar", views.alunos_em_disciplinas_salvar, name="disciplina_cursada_salvar")
]

mysite/root/urls.py
from django.urls import path
from . import views

app_name = "root"

"""Configurando as urls para a página root"""
urlpatterns = [
    path("", views.index, name="index")
]

mysite/api_integration/models/professor.py
from typing import Any
from . pessoa import Pessoa

class Professor(Pessoa):
    """Model para a entidade Professor, herda Pessoa."""

    def __call__(self, *args: Any, **kwds: Any) -> Any:
        return super().__call__(*args, **kwds)
    

mysite/login/views.py
import os
import sys
from datetime import datetime, timedelta
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpRequest, HttpResponseRedirect
from api_integration import api, utils

# Fazendo conexão com o banco de dados.
conn = api.Connection(os.environ["API_URL"])

# Fazendo o cadastro inicial caso necessário
first_user = api.AnalistaRH(
    nome=os.environ["FIRST_USER_NAME"],
    cpf=int(os.environ["FIRST_USER_CPF"]),
    rg=int(os.environ["FIRST_USER_RG"]),
    telefone=int(os.environ["FIRST_USER_TELEFONE"]),
    email=os.environ["FIRST_USER_EMAIL"]
)
response = conn.startup(first_user)

if response.status_code == 200:
    input("AVISO: foi efetuada a criação da conta inicial no banco de dados (StartUp). Os dados utilizados para criação desta conta podem ser vizualidados no arquivo .env caso exista.\nPressione ENTER para continuar...")

# Create your views here.

def index(request):
    """Retorna a página padrão para o usuário realizar o login."""
    # Verificando se o usuário já está conectado, e redirecionando caso a resposta for sim.
    logged, login = is_logged(request)
    print(f"is logged? {logged} | id: {login.id} | cargo: {login.cargo}")
    if logged:
        return get_cargo_redirect(request, True)
    
    # Retornando a página de login.
    context = {
        "erros": {"vazio":[]}
    }
    return render(request, "login/index.html", context)


def connect(request: HttpRequest) -> HttpResponse:
    """Para ser usada em uma tag form, retorna o token e o refresh_token caso validado."""
    # Pegando os parâmetros na query.
    id = request.GET.get("id", "")
    senha = request.GET.get("senha", "")

    # Validando os parâmetros.
    erros = {"vazio":[], "401":False, "426":False}
    if id == "":
        erros["vazio"].append("id")
    if senha == "":
        erros["vazio"].append("senha")
    elif not id.isnumeric():
        erros["401"] = True

    # Fazendo um request na API para efetuar o login.
    if len(erros["vazio"]) == 0 and not erros["401"]:
        response = conn.login(id, senha)

        # Validando o resultado.
        if response.status_code == 200: # OK
            login = utils.Login()
            login.set_values_with_response(response)

            # Verificando o tipo de conta
            if login.cargo in utils.Cargo.TODOS:
                r = get_cargo_redirect(login.cargo)
            else:
                r = HttpResponse(f"id: {login.id}<br>token: {login.token}<br>refresh_token: {login.refresh_token}")

            # Montando o HttpResponse. (MUDAR PARA PÁGINS DPS)
            r = set_cookies(r, login)
            return r
        
        elif response.status_code == 401: # Unauthorized
            erros["401"] = True
        
        elif response.status_code == 426: # UpgradeRequired
            erros["426"] = True

    # Renderizando a página html
    context = {
        "erros": erros
    }
    return render(request, "login/index.html", context)

def index_mudar_senha(request):
    """Retorna a página padrão para o usuário realizar o login."""
    context = {
        "erros": {"vazio":[]}
    }
    return render(request, "mudar_senha/index.html", context)


def mudar_senha(request) -> HttpResponse:
    """Mudar a senha de uma conta."""
    # Pegando os parâmetros na query.
    id = request.GET.get("id", "")
    senha_antiga = request.GET.get("senha_antiga", "")
    senha_nova = request.GET.get("senha_nova", "")

    # Validando os parâmetros.
    erros = {"vazio":[], "400":False, "401":False}
    if id == "" or not id.isnumeric():
        erros["vazio"].append("id")
    if senha_antiga == "":
        erros["vazio"].append("senha_antiga")
    if senha_nova == "":
        erros["vazio"].append("senha_nova")

    # Fazendo um request na API para efetuar o login.
    if len(erros["vazio"]) == 0:
        response = conn.mudar_senha(int(id), senha_antiga, senha_nova)

        # Validando o resultado.
        if response.status_code == 200: # OK
            # Montando o HttpResponse. (MUDAR PARA PÁGINS DPS)
            return redirect("login:index")
        
        elif response.status_code == 400: # BadRequest
            erros["400"] = True
        
        elif response.status_code == 401: # Unauthorized
            erros["401"] = True

    # Renderizando a página html
    context = {
        "erros": erros
    }
    print(context)
    return render(request, "mudar_senha/index.html", context)


def refresh_token(request, id, senha):
    """Retorna um novo token para garantir que o usuário continue logado (caso o refresh_token seja válido)."""
    return HttpResponse("GET refrsh_token")


def sair(request):
    # Montando o HttpResponse. (MUDAR PARA PÁGINS DPS)
    expires = datetime.utcnow() + timedelta(days=7)
    return set_cookies(redirect("login:index"), api.Login())


def get_cargo_redirect(request_or_str, is_request: bool = False) -> HttpResponseRedirect:
    if is_request:
        cargo = request_or_str.COOKIES[os.environ['API_USER_CARGO']]
    else:
        cargo = request_or_str
    return redirect(f"{cargo.lower()}:index")


def is_logged(request: HttpRequest) -> [bool, api.Login]:
    """Verifique se um usuário está logado ou não.
    \nCaso esteja logado, retorna um HttpResponseRedirect para a sua respectiva área.
    \nCaso contrário, retorna None."""
    # Tentando instanciar um objeto do tipo Login.
    login = api.Login()
    try:
        login.token = request.COOKIES[os.environ['API_TOKEN']]
        login.refresh_token = request.COOKIES[os.environ['API_REFRESH_TOKEN']]
        login.cargo = request.COOKIES[os.environ['API_USER_CARGO']]
        login.id = int(request.COOKIES[os.environ['API_USER_ID']])
    except Exception as e:
        return False, login
    
    # Verificando o cargo do usuário em questão.
    if login.cargo == utils.Cargo.ANALISTARH:
        response, analistarh = conn.consultar.analistarh(login.token, login.id)
    elif login.cargo == utils.Cargo.SECRETARIO:
        response, secretario = conn.consultar.secretario(login.token, login.id)
    elif login.cargo == utils.Cargo.PROFESSOR:
        response, professor = conn.consultar.professor(login.token, login.id)
    elif login.cargo == utils.Cargo.ALUNO:
        response, aluno = conn.consultar.aluno(login.token, login.id)
    else:
        return False, login
    
    print(response.status_code)
    # Resultado da requisição.
    if response.status_code == 401:
        # Verificando se o refresh_token é válido
        refresh = conn.refresh(login.id, login.token, login.refresh_token)
        print(refresh.status_code)
        if refresh.status_code == 400:
            return False, login
    
    # Caso tenha passado por todas as validações.
    return True, login

def set_cookies(r: HttpResponse, login: api.Login) -> HttpResponse:
    expires = datetime.utcnow() + timedelta(days=7)
    r.set_cookie(os.environ["API_TOKEN"], login.token, expires=expires)
    r.set_cookie(os.environ["API_REFRESH_TOKEN"], login.refresh_token, expires=expires)
    r.set_cookie(os.environ["API_USER_CARGO"], login.cargo, expires=expires)
    r.set_cookie(os.environ["API_USER_ID"], login.id, expires=expires)
    return r

mysite/login/templates/professor/acessar_conteudos.html
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Área do Professor</title>
    {% load static %}
    <link rel="shortcut icon" href="{% static 'icons/favicon.png'%}" type="image/x-icon">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/area.css'%}">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/area_header.css'%}">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/area_main.css'%}">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/area_footer.css'%}">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/manter.css'%}">
    {% load static %}
    <script src="{% static 'js/manter.js' %}"></script>
</head>
<body>
    <!-- Header, o cabeçalho da página -->
    <header>
        <!-- Ícone do sistema-->
        <div id="header-favicon">
            <img src="{% static 'icons/favicon.png' %}" alt="Íone da Universidade">
        </div>

        <!-- Título (h1) da página -->
        <div id="header-title">
            <h1>
                <a href="{% url 'professor:index'%}">Área do Professor</a>
                <span class="subtitle"> / Disciplina Ministrada / Conteudo</span>
            </h1>
            <p>Olá, {{professor.nome}}!</p>
        </div>

        <!-- Botões do cabeçalho-->
        <div id="header-buttons">
            <!-- Botão sair (link para a rota no Back End) -->
            <div id="sair-button">
                <a href="{% url 'login:sair' %}">Sair</a>
            </div>
            
            <!-- Botão trocar de senha (link para a rota no Back End) -->
            <div id="trocar-de-senha-button">
                <a href="{% url 'login:mudar_senha_pag' %}">Trocar de Senha</a>
            </div>
        </div>

        <div class="clear"></div>
    </header>

    <!-- Main, onde fica todo o conteúdo principal da página -->
    <main>
        <section> <!-- Coloque o conteúdo dentro desta seção, pois ela é centralizada -->
            <div class="container"> 
                <div id="retornos">
                    {% if status.200 %} <div class="block-success">Cadastro/Alteração realizado(a) com sucesso.</div> {% endif %}
                    {% if status.200_delete %} <div class="block-success">Cadastro apagado com sucesso.</div> {% endif %}
                    {% if status.delete_error %} <div class="block-erro">Erro ao apagar cadastro.</div> {% endif %}
                    {% if status.418 %} <div class="block-erro">Este cadastro não pode ser deletado pois está relacionado à outros.</div> {% endif %}
                    {% if status.400 %} <div class="block-erro">Um ou mais dados inseridos são inválidos.</div> {% endif %}
                    {% if status.409 %} <div class="block-erro">Um ou mais dados já pertecem a outro cadastro.</div> {% endif %}
                    {% if status.500 %} <div class="block-erro">Ocorreu um erro com o servidor.</div> {% endif %}
                </div>
                <form action="" method="get">
                    <button type="button" onclick="redirect_to_cad(`{% url 'professor:info_conteudo' %}`, null)">
                        <img src="{% static 'icons/favicon.png' %}" alt="">
                        <span>Novo</span>
                    </button>
                    <div style="clear: both;"></div>
                </form>
                <table>
                    <tr>
                        <th>Nome do Documento</th>
                        <th></th>
                        <th></th>
                    </tr>
                    {% for item in resultados %}
                    <tr class="table-row-non-clickabe">
                        <td>{{ item.documento_url }}</td>
                        <td class="doc_btn_download" onclick="redirect_to_cad(`{% url 'professor:info_conteudo' %}`, `{{ item.id }}`)">Editar</td>
                        <td class="doc_btn_download last-table-item"><a target="_blank" href="
                            {% url 'professor:download_conteudo' %}?file_name={{ item.documento_url }}
                            ">Download</a></td>
                    </tr>
                    {% endfor %}
                </table>
        </section>
    </main>

    <!-- Footer, o rodapé da página -->
    <footer>
        <!-- Primeira seção do rodapé -->
        <section id="footer-section-1">
            <h2>Sobre</h2>
            <p>PIM do 4° Semestre</p>
            <p>Grupo: DS4.4</p>
        </section>

        <!-- Segunda seção do rodapé -->
        <section id="footer-section-2">
            <h2>Atribuições</h2>
            <p><a href="https://www.flaticon.com/br/icones-gratis/universidade" class="link" target="_blank">Favicon by Flaticon</a></p>
            <p><a href="https://www.freepik.com" class="link" target="_blank">Icons by Freepik</a></p>
        </section>
    </footer>
</body>
</html>

mysite/login/templates/professor/alunos_em_disciplina.html
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Área do Professor</title>
    {% load static %}
    <link rel="shortcut icon" href="{% static 'icons/favicon.png'%}" type="image/x-icon">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/area.css'%}">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/area_header.css'%}">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/area_main.css'%}">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/area_footer.css'%}">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/manter.css'%}">
    {% load static %}
    <script src="{% static 'js/manter.js' %}"></script>
</head>
<body>
    <!-- Header, o cabeçalho da página -->
    <header>
        <!-- Ícone do sistema-->
        <div id="header-favicon">
            <img src="{% static 'icons/favicon.png' %}" alt="Íone da Universidade">
        </div>

        <!-- Título (h1) da página -->
        <div id="header-title">
            <h1>
                <a href="{% url 'professor:index'%}">Área do Professor</a>
                <span class="subtitle"> / Disciplinas / Alunos</span>
            </h1>
            <p>Olá, {{professor.nome}}!</p>
        </div>

        <!-- Botões do cabeçalho-->
        <div id="header-buttons">
            <!-- Botão sair (link para a rota no Back End) -->
            <div id="sair-button">
                <a href="{% url 'login:sair' %}">Sair</a>
            </div>
            
            <!-- Botão trocar de senha (link para a rota no Back End) -->
            <div id="trocar-de-senha-button">
                <a href="{% url 'login:mudar_senha_pag' %}">Trocar de Senha</a>
            </div>
        </div>

        <div class="clear"></div>
    </header>

    <!-- Main, onde fica todo o conteúdo principal da página -->
    <main>
        <section> <!-- Coloque o conteúdo dentro desta seção, pois ela é centralizada -->
            <div class="container"> 
                <form action="" method="get">
                    <input type="text" name="filtro" id="filtro" placeholder='Insira o nome do aluno para filtrar'>
                    <button style="width: 110px;" type="button" onclick="alunos_em_disciplina(`{% url 'professor:alunos_em_disciplinas' %}`, `{{ disciplina }}`, `{{ curso }}`, true)">
                        <img src="{% static 'icons/lupa_pesquisa.png' %}" alt="">
                        <span>Pesquisar</span>
                    </button>
                    <!-- <input type="submit" value="Pesquisar">
                    <input type="button" value="Novo"> -->
                    <div style="clear: both;"></div>
                </form>
                <table>
                    <tr>
                        <th>ID</th>
                        <th>Nome</th>
                        <th>CPF</th>
                        <th>RG</th>
                    </tr>
                    
                    {% for item in resultados %}
                    <tr class="table-row-clickabe" onclick="redirect_to_cad(`{% url 'professor:info_alunos_em_disciplinas' %}`, `{{ item.id }}`)">
                        <td>{{ item.curso_matriculado.aluno.id }}</td>
                        <td>{{ item.curso_matriculado.aluno.nome }}</td>
                        <td>{{ item.curso_matriculado.aluno.cpf }}</td>
                        <td class="last-table-item">{{ item.curso_matriculado.aluno.rg }}</td>
                    </tr>
                    {% endfor %}
                </table>
        </section>
    </main>

    <!-- Footer, o rodapé da página -->
    <footer>
        <!-- Primeira seção do rodapé -->
        <section id="footer-section-1">
            <h2>Sobre</h2>
            <p>PIM do 4° Semestre</p>
            <p>Grupo: DS4.4</p>
        </section>

        <!-- Segunda seção do rodapé -->
        <section id="footer-section-2">
            <h2>Atribuições</h2>
            <p><a href="https://www.flaticon.com/br/icones-gratis/universidade" class="link" target="_blank">Favicon by Flaticon</a></p>
            <p><a href="https://www.freepik.com" class="link" target="_blank">Icons by Freepik</a></p>
        </section>
    </footer>
</body>
</html>

mysite/login/templates/professor/index.html
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Área do Professor</title>
    {% load static %}
    <link rel="shortcut icon" href="{% static 'icons/favicon.png'%}" type="image/x-icon">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/area.css'%}">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/area_header.css'%}">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/area_main.css'%}">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/area_footer.css'%}">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/area_do_analistarh.css'%}">
</head>
<body>
    <!-- Header, o cabeçalho da página -->
    <header>
        <!-- Ícone do sistema-->
        <div id="header-favicon">
            <img src="{% static 'icons/favicon.png'%}" alt="Íone da Universidade">
        </div>

        <!-- Título (h1) da página -->
        <div id="header-title">
            <h1>Área do Professor</h1>
            <p>Olá, {{ professor.nome }}!</p>
        </div>

        <!-- Botões do cabeçalho-->
        <div id="header-buttons">
            <!-- Botão sair (link para a rota no Back End) -->
            <div id="sair-button">
                <a href="{% url 'login:sair' %}">Sair</a>
            </div>
            
            <!-- Botão trocar de senha (link para a rota no Back End) -->
            <div id="trocar-de-senha-button">
                <a href="{% url 'login:mudar_senha_pag' %}">Trocar de Senha</a>
            </div>
        </div>

        <div class="clear"></div>
    </header>

    <!-- Main, onde fica todo o conteúdo principal da página -->
    <main>
        <section> <!-- Coloque o conteúdo dentro desta seção, pois ela é centralizada -->
            <div class="container">
                <div class="option-item">
                    <a href="{% url 'professor:disciplinas'  %}">
                        <div class="option-item-icon">
                            <img src="{% static 'icons/manter_disciplinaemcurso.png'%}" alt="">
                        </div>
                        <h2>Disciplinas Ministradas</h2>
                    </a>
                </div>
                <div class="option-item">
                    <a href="{% url 'professor:mapa_de_notas'  %}">
                        <div class="option-item-icon">
                            <img src="{% static 'icons/emitir_boletim.png'%}" alt="">
                        </div>
                        <h2>Mapa de Notas</h2>
                    </a>
                </div>
                <div class="option-item">
                    <a href="{% url 'professor:conteudo'  %}">
                        <div class="option-item-icon">
                            <img src="{% static 'icons/relatorio_matricula.png'%}" alt="">
                        </div>
                        <h2>Conteúdos Programáticos</h2>
                    </a>
                </div>
        </section>
    </main>

    <!-- Footer, o rodapé da página -->
    <footer>
        <!-- Primeira seção do rodapé -->
        <section id="footer-section-1">
            <h2>Sobre</h2>
            <p>PIM do 4° Semestre</p>
            <p>Grupo: DS4.4</p>
        </section>

        <!-- Segunda seção do rodapé -->
        <section id="footer-section-2">
            <h2>Atribuições</h2>
            <p><a href="https://www.flaticon.com/br/icones-gratis/universidade" class="link" target="_blank">Favicon by Flaticon</a></p>
            <p><a href="https://www.freepik.com" class="link" target="_blank">Icons by Freepik</a></p>
        </section>
    </footer>
</body>
</html>

mysite/login/templates/professor/info_conteudo.html
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Área do Professor</title>
    {% load static %}
    <link rel="shortcut icon" href="{% static 'icons/favicon.png'%}" type="image/x-icon">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/area.css'%}">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/area_header.css'%}">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/area_main.css'%}">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/area_footer.css'%}">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/info.css'%}">
    {% load static %}
    <script src="{% static 'js/manter.js' %}"></script>
</head>
<body>
    <!-- Header, o cabeçalho da página -->
    <header>
        <!-- Ícone do sistema-->
        <div id="header-favicon">
            <img src="{% static 'icons/favicon.png' %}" alt="Íone da Universidade">
        </div>

        <!-- Título (h1) da página -->
        <div id="header-title">
            <h1>
                <a href="{% url 'professor:index'%}">Área do Professor</a>
                <span class="subtitle"> / Conteudo</span>
            </h1>
            <p>Olá, {{professor.nome}}!</p>
        </div>

        <!-- Botões do cabeçalho-->
        <div id="header-buttons">
            <!-- Botão sair (link para a rota no Back End) -->
            <div id="sair-button">
                <a href="{% url 'login:sair' %}">Sair</a>
            </div>
            
            <!-- Botão trocar de senha (link para a rota no Back End) -->
            <div id="trocar-de-senha-button">
                <a href="{% url 'login:mudar_senha_pag' %}">Trocar de Senha</a>
            </div>
        </div>

        <div class="clear"></div>
    </header>

    <!-- Main, onde fica todo o conteúdo principal da página -->
    <main>
        <section> <!-- Coloque o conteúdo dentro desta seção, pois ela é centralizada -->
            <div class="container"> 
                <div id="retornos">
                    {% if status.200 %} <div class="block-success">Cadastro/Alteração realizado(a) com sucesso.</div> {% endif %}
                    {% if status.200_delete %} <div class="block-success">Cadastro apagado com sucesso.</div> {% endif %}
                    {% if status.delete_error %} <div class="block-erro">Erro ao apagar cadastro.</div> {% endif %}
                    {% if status.400 %} <div class="block-erro">Um ou mais dados inseridos são inválidos.</div> {% endif %}
                    {% if status.409 %} <div class="block-erro">Um ou mais dados já pertecem a outro cadastro.</div> {% endif %}
                    {% if status.418 %} <div class="block-erro">Este cadastro não pode ser deletado pois está relacionado à outros.</div> {% endif %}
                    {% if status.500 %} <div class="block-erro">Ocorreu um erro com o servidor.</div> {% endif %}
                </div>
                <form action="{% url 'professor:conteudo_salvar'  %}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div>
                        {% if cadastro != None %}
                        <button type="button" onclick="redirect_to_cad(`{% url 'professor:conteudo_apagar' %}`,
                        `{{ cadastro.id }}`)">
                            <img src="{% static 'icons/apagar.png' %}" alt="">
                            <span>Apagar</span>
                        </button>
                        <input type="text" name="id" id="id" value="{{ cadastro.id }}" style="display: none;">
                        {% endif %}
                        <button type="submit">
                            <img src="{% static 'icons/novo.png' %}" alt="">
                            <span>Salvar</span>
                        </button>
                        <div style="clear: both;"></div>
                    </div>
            
                    <div class="form-input" {% if cadastro != None %} style="display: none;" {% endif %}>
                        <input class="input" type="text" name="nome_turma" id="nome_turma" placeholder="Insira o nome da turma aqui" required
                        {% if cadastro != None %} value="{{ cadastro.disciplina_ministrada.turma.nome }}" {% endif %}>
                        <label for="nome_turma">Turma</label>
                    </div>
                    <div class="form-input" {% if cadastro != None %} style="display: none;" {% endif %}>
                        <input class="input" type="text" name="nome_disciplina" id="nome_disciplina" placeholder="Insira o nome da disciplina aqui" required
                        {% if cadastro != None %} value="{{ cadastro.disciplina_ministrada.disciplina.nome }}" {% endif %}>
                        <label for="nome_disciplina">Disciplina</label>
                    </div>

                    <div class="form-input-file">
                        <input class="input-file" type="file" name="documento" id="documento" accept=".pdf" required>
                        <label for="documento">Documento</label>
                    </div>
                    <div style="clear: both;"></div>
                </form>
        </section>
    </main>

    <!-- Footer, o rodapé da página -->
    <footer>
        <!-- Primeira seção do rodapé -->
        <section id="footer-section-1">
            <h2>Sobre</h2>
            <p>PIM do 4° Semestre</p>
            <p>Grupo: DS4.4</p>
        </section>

        <!-- Segunda seção do rodapé -->
        <section id="footer-section-2">
            <h2>Atribuições</h2>
            <p><a href="https://www.flaticon.com/br/icones-gratis/universidade" class="link" target="_blank">Favicon by Flaticon</a></p>
            <p><a href="https://www.freepik.com" class="link" target="_blank">Icons by Freepik</a></p>
        </section>
    </footer>
</body>
</html>