mysite/aluno/urls.py
from django.urls import path
from . import views

app_name = "aluno"

"""Configurando as urls para a página de login"""
urlpatterns = [
    path("", views.index, name="index"),
    path("curso", views.acessar_cursos, name="acessar_cursos"),
    path("curso/disciplina", views.acessar_disciplinas, name="acessar_disciplinas"),
    path("curso/disciplina/conteudo", views.acessar_conteudos, name="acessar_conteudos"),
    path("curso/disciplina/conteudo/download", views.download_conteudo, name="download_conteudo"),
    path("notas_e_faltas", views.notas_e_faltas, name="notas_e_faltas"),
    
    path("declaracao", views.download_declaracao, name="declaracao"),
    path("historico", views.download_historico, name="historico"),
    path("relatorio", views.download_relatorio, name="relatorio"),
    path("boletim", views.download_boletim, name="boletim")
]

mysite/login/urls.py
from django.urls import path
from . import views

app_name = "login"

"""Configurando as urls para a página de login"""
urlpatterns = [
    path("", views.index, name="index"),
    path("connect", views.connect, name="connect"), #"^(?P<id>[\w-]+)/$"
    path("mudar_senha", views.index_mudar_senha, name="mudar_senha_pag"),
    path("mudar_senha/mudar", views.mudar_senha, name="mudar"),
    path("sair", views.sair, name="sair")
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from dotenv import load_dotenv
import os

# Setando as minhas próprias variáveis de ambiente
load_dotenv()
print(os.environ["API_URL"])

urlpatterns = [
    path("", include("root.urls")),
    path("admin/", admin.site.urls),
    path("login/", include("login.urls")),
    path("erros/", include("errors.urls")),
    path("analistarh/", include("analistarh.urls")),
    path("secretario/", include("secretario.urls")),
    path("professor/", include("professor.urls")),
    path("aluno/", include("aluno.urls"))
]

mysite/root/urls.py
from django.urls import path
from . import views

app_name = "root"

"""Configurando as urls para a página root"""
urlpatterns = [
    path("", views.index, name="index")
]

mysite/api_integration/models/aluno.py
from typing import Any
from . pessoa import Pessoa

class Aluno(Pessoa):
    """Model para a entidade Aluno, herda Pessoa."""

    def __call__(self, *args: Any, **kwds: Any) -> Any:
        return super().__call__(*args, **kwds)
    

mysite/aluno/views.py
import os, json
from datetime import datetime
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpRequest, FileResponse
from api_integration import api, utils
from login.views import is_logged, set_cookies

conn = api.Connection(os.environ["API_URL"])

def verificar_pasta_arquivos_temporarios():
    pasta = os.getcwd() + "\\arquivos_temporarios\\"
    if not os.path.isdir(pasta):
        os.mkdir(pasta)

def apagar_todos_os_arquivos_temporarios():
    pasta = os.getcwd() + "\\arquivos_temporarios\\"
    for file in os.listdir(pasta):
        os.remove(os.path.join(pasta, file))

def check_login(request: HttpRequest) -> [dict, api.Login]:
    # Verificando se o usuário está logado.
    logged, login = is_logged(request)
    if not logged:
        return redirect("login:index"), login

    # Fazendo o request na API
    response, aluno = conn.consultar.aluno(login.token, login.id)
    context = {
        "erros":[]
    }

    # Caso o token esteja expirado.
    if response.status_code == 401:
        # Verificando se o refresh_token é válido
        refresh = conn.refresh(login.id, login.token, login.refresh_token)
        if refresh.status_code == 400:
            return redirect("login:index"), login
        
        # Caso o refresh tenha tido êxito
        login = api.Login()
        login.set_values_with_response(refresh)
        # Fazendo o request na API novamente com o novo token
        response, aluno = conn.consultar.aluno(login.token, login.id)

    # Caso o token seja válido, mas o usuário não tenha permissão para usar o endpoint.
    elif response.status_code == 403 or login.cargo != utils.Cargo.ALUNO:
        return redirect("erros:403"), login
    
    # Caso tudo ocorra bem
    context["aluno"] = aluno
    return context, login

# Create your views here.
def index(request: HttpRequest):
    """Página inicial da área do aluno de RH"""
    context, login = check_login(request)
    if not isinstance(context, dict):
        return context

    # Adicionando o obj ao contexto e respondendo o request.
    return set_cookies(render(request, "aluno/index.html", context), login)

def acessar_cursos(request: HttpRequest):
    """Página inicial para buscas de curso"""
    context, login = check_login(request)
    if not isinstance(context, dict):
        return context
    
    filtro = request.GET.get("filtro", "")
    response, cms = conn.procurar.curso_matriculado(login.token, login.id)
    context["resultados"] = []
    
    # Apenas os do aluno
    for cm in cms:
        if filtro in cm.curso.nome or filtro == "":
            context["resultados"].append(cm)
    
    # Adicionando o obj ao contexto e respondendo o request.
    return set_cookies(render(request, "aluno/acessar_cursos.html", context), login)

def acessar_disciplinas(request: HttpRequest):
    """Página inicial para buscas de curso"""
    context, login = check_login(request)
    if not isinstance(context, dict):
        return context
    
    filtro = request.GET.get("filtro", "")
    curso_matriculado = request.GET.get("curso_matriculado", "")
    response, dcs = conn.procurar.disciplina_cursada(login.token, curso_matriculado)
    context["resultados"] = []
    
    # Apenas os do aluno
    for dc in dcs:
        if filtro in dc.disciplina.nome or filtro == "":
            context["resultados"].append(dc)
    
    # Adicionando o obj ao contexto e respondendo o request.
    return set_cookies(render(request, "aluno/acessar_disciplinas.html", context), login)

def acessar_conteudos(request: HttpRequest):
    """Página inicial para buscas de curso"""
    context, login = check_login(request)
    if not isinstance(context, dict):
        return context
    
    turma = request.GET.get("turma", "")
    disciplina = request.GET.get("disciplina", "")
    print(turma, disciplina)
    
    professores = conn.consultar.turma(login.token, turma)[1].professores 
    disciplina_ministrada = None
    for p in professores:
        dms = conn.procurar.disciplina_ministrada(login.token, p.id)[1]
        for dm in dms:
            if dm.disciplina.id == disciplina:
                disciplina_ministrada = dm.id
                
    conteudos = conn.procurar.conteudo(login.token, disciplina_ministrada)[1]
    for c in range(0, len(conteudos)):
        conteudos[c].documento_url = conteudos[c].documento_url.replace("/api/file/conteudo/", "")
    context["resultados"] = conteudos
    
    # Adicionando o obj ao contexto e respondendo o request.
    return set_cookies(render(request, "aluno/acessar_conteudos.html", context), login)

def download_conteudo(request: HttpRequest):
    """Página inicial para buscas de curso"""
    context, login = check_login(request)
    if not isinstance(context, dict):
        return context
    
    verificar_pasta_arquivos_temporarios()
    apagar_todos_os_arquivos_temporarios()
    file_path = os.path.join(os.getcwd() + "\\arquivos_temporarios\\", request.GET.get("file_name", ""))
    response = conn.arquivo.conteudo(login.token, request.GET.get("file_name", ""))

    filew = open(file_path, 'wb')
    filew.write(response.content)
    filew.close()

    return FileResponse(open(file_path, "rb"), as_attachment=True)

def notas_e_faltas(request: HttpRequest):
    """Página inicial para buscas de curso"""
    context, login = check_login(request)
    if not isinstance(context, dict):
        return context
    
    filtro = request.GET.get("filtro", "")
    cms = conn.procurar.curso_matriculado(login.token, login.id)[1]
    context["resultados"] = []
    
    # Apenas os do curso
    for cm in cms:
        if filtro in cm.curso.nome or filtro == "":
            for d in cm.disciplinas:
                dcs = conn.procurar.disciplina_cursada(login.token, cm.id)[1]
                print(dcs)
                context["resultados"] += dcs
                print(context["resultados"])
    
    # Adicionando o obj ao contexto e respondendo o request.
    return set_cookies(render(request, "aluno/notas_e_faltas.html", context), login)


def download_declaracao(request: HttpRequest):
    context, login = check_login(request)
    if not isinstance(context, dict):
        return context
    verificar_pasta_arquivos_temporarios()
    apagar_todos_os_arquivos_temporarios()

    file_name = "declaracao (" + datetime.now().strftime("%d_%m_%Y as %H horas e %M minutos") + ").pdf"
    file_path = os.path.join(os.getcwd() + "\\arquivos_temporarios\\", file_name)
    response = conn.arquivo.declaracao(login.token, str(login.id))

    filew = open(file_path, 'wb')
    filew.write(response.content)
    filew.close()

    return FileResponse(open(file_path, "rb"), as_attachment=True)

def download_historico(request: HttpRequest):
    context, login = check_login(request)
    if not isinstance(context, dict):
        return context
    verificar_pasta_arquivos_temporarios()
    apagar_todos_os_arquivos_temporarios()

    file_name = "historico (" + datetime.now().strftime("%d_%m_%Y as %H horas e %M minutos") + ").pdf"
    file_path = os.path.join(os.getcwd() + "\\arquivos_temporarios\\", file_name)
    response = conn.arquivo.historico(login.token, str(login.id))

    filew = open(file_path, 'wb')
    filew.write(response.content)
    filew.close()

    return FileResponse(open(file_path, "rb"), as_attachment=True)

def download_relatorio(request: HttpRequest):
    context, login = check_login(request)
    if not isinstance(context, dict):
        return context
    verificar_pasta_arquivos_temporarios()
    apagar_todos_os_arquivos_temporarios()

    file_name = "relatorio (" + datetime.now().strftime("%d_%m_%Y as %H horas e %M minutos") + ").pdf"
    file_path = os.path.join(os.getcwd() + "\\arquivos_temporarios\\", file_name)
    response = conn.arquivo.relatorio(login.token, str(login.id))

    filew = open(file_path, 'wb')
    filew.write(response.content)
    filew.close()

    return FileResponse(open(file_path, "rb"), as_attachment=True)

def download_boletim(request: HttpRequest):
    context, login = check_login(request)
    if not isinstance(context, dict):
        return context
    verificar_pasta_arquivos_temporarios()
    apagar_todos_os_arquivos_temporarios()

    file_name = "boletim (" + datetime.now().strftime("%d_%m_%Y as %H horas e %M minutos") + ").pdf"
    file_path = os.path.join(os.getcwd() + "\\arquivos_temporarios\\", file_name)
    response = conn.arquivo.boletim(login.token, str(login.id))

    filew = open(file_path, 'wb')
    filew.write(response.content)
    filew.close()

    return FileResponse(open(file_path, "rb"), as_attachment=True)

mysite/login/templates/aluno/acessar_conteudos.html
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Área do Aluno</title>
    {% load static %}
    <link rel="shortcut icon" href="{% static 'icons/favicon.png'%}" type="image/x-icon">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/area.css'%}">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/area_header.css'%}">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/area_main.css'%}">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/area_footer.css'%}">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/manter.css'%}">
    {% load static %}
    <script src="{% static 'js/manter.js' %}"></script>
</head>
<body>
    <!-- Header, o cabeçalho da página -->
    <header>
        <!-- Ícone do sistema-->
        <div id="header-favicon">
            <img src="{% static 'icons/favicon.png' %}" alt="Íone da Universidade">
        </div>

        <!-- Título (h1) da página -->
        <div id="header-title">
            <h1>
                <a href="{% url 'aluno:index'%}">Área do Aluno</a>
                <span class="subtitle"> / Curso / Disciplina / Conteudo</span>
            </h1>
            <p>Olá, {{aluno.nome}}!</p>
        </div>

        <!-- Botões do cabeçalho-->
        <div id="header-buttons">
            <!-- Botão sair (link para a rota no Back End) -->
            <div id="sair-button">
                <a href="{% url 'login:sair' %}">Sair</a>
            </div>
            
            <!-- Botão trocar de senha (link para a rota no Back End) -->
            <div id="trocar-de-senha-button">
                <a href="{% url 'login:mudar_senha_pag' %}">Trocar de Senha</a>
            </div>
        </div>

        <div class="clear"></div>
    </header>

    <!-- Main, onde fica todo o conteúdo principal da página -->
    <main>
        <section> <!-- Coloque o conteúdo dentro desta seção, pois ela é centralizada -->
            <div class="container"> 
                <table>
                    <tr>
                        <th>Nome do Documento</th>
                        <th></th>
                    </tr>
                    {% for item in resultados %}
                    <tr class="table-row-non-clickabe">
                        <td>{{ item.documento_url }}</td>
                        <td class="doc_btn_download last-table-item"><a target="_blank" href="
                            {% url 'aluno:download_conteudo' %}?file_name={{ item.documento_url }}
                            ">Download</a></td>
                    </tr>
                    {% endfor %}
                </table>
        </section>
    </main>

    <!-- Footer, o rodapé da página -->
    <footer>
        <!-- Primeira seção do rodapé -->
        <section id="footer-section-1">
            <h2>Sobre</h2>
            <p>PIM do 4° Semestre</p>
            <p>Grupo: DS4.4</p>
        </section>

        <!-- Segunda seção do rodapé -->
        <section id="footer-section-2">
            <h2>Atribuições</h2>
            <p><a href="https://www.flaticon.com/br/icones-gratis/universidade" class="link" target="_blank">Favicon by Flaticon</a></p>
            <p><a href="https://www.freepik.com" class="link" target="_blank">Icons by Freepik</a></p>
        </section>
    </footer>
</body>
</html>

mysite/login/templates/aluno/acessar_cursos.html
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Área do Aluno</title>
    {% load static %}
    <link rel="shortcut icon" href="{% static 'icons/favicon.png'%}" type="image/x-icon">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/area.css'%}">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/area_header.css'%}">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/area_main.css'%}">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/area_footer.css'%}">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/manter.css'%}">
    {% load static %}
    <script src="{% static 'js/manter.js' %}"></script>
</head>
<body>
    <!-- Header, o cabeçalho da página -->
    <header>
        <!-- Ícone do sistema-->
        <div id="header-favicon">
            <img src="{% static 'icons/favicon.png' %}" alt="Íone da Universidade">
        </div>

        <!-- Título (h1) da página -->
        <div id="header-title">
            <h1>
                <a href="{% url 'aluno:index'%}">Área do Aluno</a>
                <span class="subtitle"> / Curso</span>
            </h1>
            <p>Olá, {{aluno.nome}}!</p>
        </div>

        <!-- Botões do cabeçalho-->
        <div id="header-buttons">
            <!-- Botão sair (link para a rota no Back End) -->
            <div id="sair-button">
                <a href="{% url 'login:sair' %}">Sair</a>
            </div>
            
            <!-- Botão trocar de senha (link para a rota no Back End) -->
            <div id="trocar-de-senha-button">
                <a href="{% url 'login:mudar_senha_pag' %}">Trocar de Senha</a>
            </div>
        </div>

        <div class="clear"></div>
    </header>

    <!-- Main, onde fica todo o conteúdo principal da página -->
    <main>
        <section> <!-- Coloque o conteúdo dentro desta seção, pois ela é centralizada -->
            <div class="container"> 
                <form action="" method="get">
                    <input type="text" name="filtro" id="filtro" placeholder="Insira o nome do curso para filtrar">
                    <button type="submit">
                        <img src="{% static 'icons/lupa_pesquisa.png' %}" alt="">
                        <span>Pesquisar</span>
                    </button>
                    <!-- <input type="submit" value="Pesquisar">
                    <input type="button" value="Novo"> -->
                    <div style="clear: both;"></div>
                </form>
                <table>
                    <tr>
                        <th>Curso</th>
                        <th>Turma</th>
                        <th>Trancado</th>
                        <th>Finalizado</th>

                    </tr>
                    {% for item in resultados %}
                    <tr class="table-row-clickabe" onclick="redirect_to_cad(`{% url 'aluno:acessar_disciplinas' %}`, `{{ item.id }}` + `&curso_matriculado={{ item.id }}`)">
                        <td>{{ item.curso.nome }}</td>
                        <td>{{ item.turma.nome }}</td>
                        <td>{% if item.trancado %}Sim{% else %}Não{% endif %}</td>
                        <td class="last-table-item">{% if item.finalizado %}Sim{% else %}Não{% endif %}</td>
                    </tr>
                    {% endfor %}
                </table>
        </section>
    </main>

    <!-- Footer, o rodapé da página -->
    <footer>
        <!-- Primeira seção do rodapé -->
        <section id="footer-section-1">
            <h2>Sobre</h2>
            <p>PIM do 4° Semestre</p>
            <p>Grupo: DS4.4</p>
        </section>

        <!-- Segunda seção do rodapé -->
        <section id="footer-section-2">
            <h2>Atribuições</h2>
            <p><a href="https://www.flaticon.com/br/icones-gratis/universidade" class="link" target="_blank">Favicon by Flaticon</a></p>
            <p><a href="https://www.freepik.com" class="link" target="_blank">Icons by Freepik</a></p>
        </section>
    </footer>
</body>
</html>

mysite/login/templates/aluno/acessar_disciplinas.html
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Área do Aluno</title>
    {% load static %}
    <link rel="shortcut icon" href="{% static 'icons/favicon.png'%}" type="image/x-icon">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/area.css'%}">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/area_header.css'%}">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/area_main.css'%}">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/area_footer.css'%}">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/manter.css'%}">
    {% load static %}
    <script src="{% static 'js/manter.js' %}"></script>
</head>
<body>
    <!-- Header, o cabeçalho da página -->
    <header>
        <!-- Ícone do sistema-->
        <div id="header-favicon">
            <img src="{% static 'icons/favicon.png' %}" alt="Íone da Universidade">
        </div>

        <!-- Título (h1) da página -->
        <div id="header-title">
            <h1>
                <a href="{% url 'aluno:index'%}">Área do Aluno</a>
                <span class="subtitle"> / Curso / Disciplina</span>
            </h1>
            <p>Olá, {{aluno.nome}}!</p>
        </div>

        <!-- Botões do cabeçalho-->
        <div id="header-buttons">
            <!-- Botão sair (link para a rota no Back End) -->
            <div id="sair-button">
                <a href="{% url 'login:sair' %}">Sair</a>
            </div>
            
            <!-- Botão trocar de senha (link para a rota no Back End) -->
            <div id="trocar-de-senha-button">
                <a href="{% url 'login:mudar_senha_pag' %}">Trocar de Senha</a>
            </div>
        </div>

        <div class="clear"></div>
    </header>

    <!-- Main, onde fica todo o conteúdo principal da página -->
    <main>
        <section> <!-- Coloque o conteúdo dentro desta seção, pois ela é centralizada -->
            <div class="container"> 
                <form action="" method="get">
                    <input type="text" name="filtro" id="filtro" placeholder="Insira o nome da disciplina para filtrar">
                    <button type="submit">
                        <img src="{% static 'icons/favicon.png' %}" alt="">
                        <span>Pesquisar</span>
                    </button>
                    <!-- <input type="submit" value="Pesquisar">
                    <input type="button" value="Novo"> -->
                    <div style="clear: both;"></div>
                </form>
                <table>
                    <tr>
                        <th>ID</th>
                        <th>Disciplina</th>
                        <th>Situacao</th>
                    </tr>
                    {% for item in resultados %}
                    <tr class="table-row-clickabe" onclick="redirect_to_cad(`{% url 'aluno:acessar_conteudos' %}`, `{{ item.id }}` 
                    + `&turma={{ item.curso_matriculado.turma.id }}`
                    + `&disciplina={{ item.disciplina.id }}`)">
                        <td>{{ item.disciplina.id }}</td>
                        <td>{{ item.disciplina.nome }}</td>
                        <td class="last-table-item">{{ item.situacao }}</td>
                    </tr>
                    {% endfor %}
                </table>
        </section>
    </main>

    <!-- Footer, o rodapé da página -->
    <footer>
        <!-- Primeira seção do rodapé -->
        <section id="footer-section-1">
            <h2>Mapa do Site</h2>
            <p><a href="{% url 'login:mudar_senha_pag' %}" class="link">Trocar de senha</a></p>
            <p><a href="{% url 'login:sair' %}" class="link">Sair</a></p>
        </section>

        <!-- Segunda seção do rodapé -->
        <section id="footer-section-2">
            <h2>Atribuições</h2>
            <p><a href="#" class="link">site - favicon nome</a></p>
            <p><a href="#" class="link">site - menu itens</a></p>
        </section>
    </footer>
</body>
</html>

mysite/login/templates/aluno/index.html
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Área do Analista de RH</title>
    {% load static %}
    <link rel="shortcut icon" href="{% static 'icons/favicon.png'%}" type="image/x-icon">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/area.css'%}">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/area_header.css'%}">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/area_main.css'%}">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/area_footer.css'%}">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/area_do_analistarh.css'%}">
</head>
<body>
    <!-- Header, o cabeçalho da página -->
    <header>
        <!-- Ícone do sistema-->
        <div id="header-favicon">
            <img src="{% static 'icons/favicon.png'%}" alt="Íone da Universidade">
        </div>

        <!-- Título (h1) da página -->
        <div id="header-title">
            <h1>Área do Aluno</h1>
            <p>Olá, {{ aluno.nome }}!</p>
        </div>

        <!-- Botões do cabeçalho-->
        <div id="header-buttons">
            <!-- Botão sair (link para a rota no Back End) -->
            <div id="sair-button">
                <a href="{% url 'login:sair' %}">Sair</a>
            </div>
            
            <!-- Botão trocar de senha (link para a rota no Back End) -->
            <div id="trocar-de-senha-button">
                <a href="{% url 'login:mudar_senha_pag' %}">Trocar de Senha</a>
            </div>
        </div>

        <div class="clear"></div>
    </header>

    <!-- Main, onde fica todo o conteúdo principal da página -->
    <main>
        <section> <!-- Coloque o conteúdo dentro desta seção, pois ela é centralizada -->
            <div class="container"> 
                <div class="option-item">
                    <a href="{% url 'aluno:acessar_cursos'  %}">
                        <div class="option-item-icon">
                            <img src="{% static 'icons/manter_curso.png'%}" alt="">
                        </div>
                        <h2>Meus Cursos</h2>
                    </a>
                </div>
                <div class="option-item">
                     <a href="{% url 'aluno:notas_e_faltas'  %}">
                        <div class="option-item-icon">
                            <img src="{% static 'icons/manter_notas.png'%}" alt="">
                        </div>
                        <h2>Notas e Faltas Semestrais</h2>
                    </a>
                </div>
                <div class="option-item">
                    <a href="{% url 'aluno:declaracao'  %}">
                        <div class="option-item-icon">
                            <img src="{% static 'icons/emitir_declaracao.png'%}" alt="">
                        </div>
                        <h2>Emitir Declaração</h2>
                    </a>
                </div>
                <div class="option-item">
                    <a href="{% url 'aluno:historico'  %}">
                        <div class="option-item-icon">
                            <img src="{% static 'icons/historico_escolar.png'%}" alt="">
                        </div>
                        <h2>Emitir Histórico Escolar</h2>
                    </a>
                </div>
                <div class="option-item">
                    <a href="{% url 'aluno:relatorio'  %}">
                        <div class="option-item-icon">
                            <img src="{% static 'icons/relatorio_matricula.png'%}" alt="">
                        </div>
                        <h2>Emitir Relatório de Matricula</h2>
                    </a>
                </div>
                <div class="option-item">
                    <a href="{% url 'aluno:boletim'  %}">
                        <div class="option-item-icon">
                            <img src="{% static 'icons/emitir_boletim.png'%}" alt="">
                        </div>
                        <h2>Emitir Boletim</h2>
                    </a>
                </div>
        </section>
    </main>

    <!-- Footer, o rodapé da página -->
    <footer>
        <!-- Primeira seção do rodapé -->
        <section id="footer-section-1">
            <h2>Sobre</h2>
            <p>PIM do 4° Semestre</p>
            <p>Grupo: DS4.4</p>
        </section>

        <!-- Segunda seção do rodapé -->
        <section id="footer-section-2">
            <h2>Atribuições</h2>
            <p><a href="https://www.flaticon.com/br/icones-gratis/universidade" class="link" target="_blank">Favicon by Flaticon</a></p>
            <p><a href="https://www.freepik.com" class="link" target="_blank">Icons by Freepik</a></p>
        </section>
    </footer>
</body>
</html>