mysite/analistarh/urls.py
from django.urls import path
from . import views

app_name = "analistarh"

"""Configurando as urls para a página de login"""
urlpatterns = [
    path("", views.index, name="index"),
    path("analistarh", views.procurar_analista, name="analistarh"),
    path("analistarh/info", views.editar_analista, name="analistarh_info"),
    path("professor", views.procurar_professor, name="professor"),
    path("professor/info", views.editar_professor, name="professor_info"),
    path("secretario", views.procurar_secretario, name="secretario"),
    path("secretario/info", views.editar_secretario, name="secretario_info"),


    path("analistarh/info/salvar", views.analistarh_salvar, name="analistarh_salvar"),
    path("professor/info/salvar", views.professor_salvar, name="professor_salvar"),
    path("secretario/info/salvar", views.secretario_salvar, name="secretario_salvar"),

    path("analistarh/info/apagar", views.analistarh_apagar, name="analistarh_apagar"),
    path("professor/info/apagar", views.professor_apagar, name="professor_apagar"),
    path("secretario/info/apagar", views.secretario_apagar, name="secretario_apagar"),
]

mysite/login/urls.py
from django.urls import path
from . import views

app_name = "login"

"""Configurando as urls para a página de login"""
urlpatterns = [
    path("", views.index, name="index"),
    path("connect", views.connect, name="connect"), #"^(?P<id>[\w-]+)/$"
    path("mudar_senha", views.index_mudar_senha, name="mudar_senha_pag"),
    path("mudar_senha/mudar", views.mudar_senha, name="mudar"),
    path("sair", views.sair, name="sair")
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from dotenv import load_dotenv
import os

# Setando as minhas próprias variáveis de ambiente
load_dotenv()
print(os.environ["API_URL"])

urlpatterns = [
    path("", include("root.urls")),
    path("admin/", admin.site.urls),
    path("login/", include("login.urls")),
    path("erros/", include("errors.urls")),
    path("analistarh/", include("analistarh.urls")),
    path("secretario/", include("secretario.urls")),
    path("professor/", include("professor.urls")),
    path("aluno/", include("aluno.urls"))
]

mysite/root/urls.py
from django.urls import path
from . import views

app_name = "root"

"""Configurando as urls para a página root"""
urlpatterns = [
    path("", views.index, name="index")
]

mysite/secretario/urls.py
from django.urls import path
from . import views

app_name = "secretario"

"""Configurando as urls para a página de login"""
urlpatterns = [
    path("", views.index, name="index"),
    path("aluno", views.procurar_aluno, name="aluno"),
    path("curso", views.procurar_curso, name="curso"),
    path("turma", views.procurar_turma, name="turma"),
    path("disciplina", views.procurar_disciplina, name="disciplina"),
    path("aluno/info", views.editar_aluno, name="aluno_info"),
    path("curso/info", views.editar_curso, name="curso_info"),
    path("turma/info", views.editar_turma, name="turma_info"),
    path("disciplina/info", views.editar_disciplina, name="disciplina_info"),

    path("professor_em_turma", views.procurar_professor_em_turma, name="professor_em_turma"),
    path("disciplina_em_curso", views.procurar_disciplina_em_curso, name="disciplina_em_curso"),
    path("aluno_em_curso", views.procurar_aluno_em_curso, name="aluno_em_curso"),
    
    path("professor_em_turma/info", views.editar_professor_em_turma, name="professor_em_turma_info"),
    path("disciplina_em_curso/info", views.editar_disciplina_em_curso, name="disciplina_em_curso_info"),
    path("aluno_em_curso/info", views.editar_aluno_em_curso, name="aluno_em_curso_info"),
    path("aluno/info", views.editar_aluno, name="editar_aluno"),
    path("curso/info", views.editar_curso, name="editar_curso"),
    path("turma/info", views.editar_turma, name="editar_turma"),
    path("disciplina/info", views.editar_disciplina, name="editar_disciplina"),


    path("professor_em_turma/info/salvar", views.professor_em_turma_salvar, name="professor_em_turma_salvar"),
    path("disciplina_em_curso/info/salvar", views.disciplina_em_curso_salvar, name="disciplina_em_curso_salvar"),
    path("aluno_em_curso/info/salvar", views.aluno_em_curso_salvar, name="aluno_em_curso_salvar"),
    path("aluno/info/salvar", views.aluno_salvar, name="aluno_salvar"),
    path("curso/info/salvar", views.curso_salvar, name="curso_salvar"),
    path("turma/info/salvar", views.turma_salvar, name="turma_salvar"),
    path("disciplina/info/salvar", views.disciplina_salvar, name="disciplina_salvar"),


    path("professor_em_turma/info/apagar", views.professor_em_turma_apagar, name="professor_em_turma_apagar"),
    path("disciplina_em_curso/info/apagar", views.disciplina_em_curso_apagar, name="disciplina_em_curso_apagar"),
    path("aluno_em_curso/info/apagar", views.aluno_em_curso_apagar, name="aluno_em_curso_apagar"),
    path("aluno/info/apagar", views.aluno_apagar, name="aluno_apagar"),
    path("curso/info/apagar", views.curso_apagar, name="curso_apagar"),
    path("turma/info/apagar", views.turma_apagar, name="turma_apagar"),
    path("disciplina/info/apagar", views.disciplina_apagar, name="disciplina_apagar")
]

mysite/api_integration/models/secretario.py
from typing import Any
from .pessoa import Pessoa

class Secretario(Pessoa):
    """Model para a entidade Secretario, herda Pessoa."""

    def __call__(self, *args: Any, **kwds: Any) -> Any:
        return super().__call__(*args, **kwds)
    

mysite/login/views.py
import os
import sys
from datetime import datetime, timedelta
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpRequest, HttpResponseRedirect
from api_integration import api, utils

# Fazendo conexão com o banco de dados.
conn = api.Connection(os.environ["API_URL"])

# Fazendo o cadastro inicial caso necessário
first_user = api.AnalistaRH(
    nome=os.environ["FIRST_USER_NAME"],
    cpf=int(os.environ["FIRST_USER_CPF"]),
    rg=int(os.environ["FIRST_USER_RG"]),
    telefone=int(os.environ["FIRST_USER_TELEFONE"]),
    email=os.environ["FIRST_USER_EMAIL"]
)
response = conn.startup(first_user)

if response.status_code == 200:
    input("AVISO: foi efetuada a criação da conta inicial no banco de dados (StartUp). Os dados utilizados para criação desta conta podem ser vizualidados no arquivo .env caso exista.\nPressione ENTER para continuar...")

# Create your views here.

def index(request):
    """Retorna a página padrão para o usuário realizar o login."""
    # Verificando se o usuário já está conectado, e redirecionando caso a resposta for sim.
    logged, login = is_logged(request)
    print(f"is logged? {logged} | id: {login.id} | cargo: {login.cargo}")
    if logged:
        return get_cargo_redirect(request, True)
    
    # Retornando a página de login.
    context = {
        "erros": {"vazio":[]}
    }
    return render(request, "login/index.html", context)


def connect(request: HttpRequest) -> HttpResponse:
    """Para ser usada em uma tag form, retorna o token e o refresh_token caso validado."""
    # Pegando os parâmetros na query.
    id = request.GET.get("id", "")
    senha = request.GET.get("senha", "")

    # Validando os parâmetros.
    erros = {"vazio":[], "401":False, "426":False}
    if id == "":
        erros["vazio"].append("id")
    if senha == "":
        erros["vazio"].append("senha")
    elif not id.isnumeric():
        erros["401"] = True

    # Fazendo um request na API para efetuar o login.
    if len(erros["vazio"]) == 0 and not erros["401"]:
        response = conn.login(id, senha)

        # Validando o resultado.
        if response.status_code == 200: # OK
            login = utils.Login()
            login.set_values_with_response(response)

            # Verificando o tipo de conta
            if login.cargo in utils.Cargo.TODOS:
                r = get_cargo_redirect(login.cargo)
            else:
                r = HttpResponse(f"id: {login.id}<br>token: {login.token}<br>refresh_token: {login.refresh_token}")

            # Montando o HttpResponse. (MUDAR PARA PÁGINS DPS)
            r = set_cookies(r, login)
            return r
        
        elif response.status_code == 401: # Unauthorized
            erros["401"] = True
        
        elif response.status_code == 426: # UpgradeRequired
            erros["426"] = True

    # Renderizando a página html
    context = {
        "erros": erros
    }
    return render(request, "login/index.html", context)

def index_mudar_senha(request):
    """Retorna a página padrão para o usuário realizar o login."""
    context = {
        "erros": {"vazio":[]}
    }
    return render(request, "mudar_senha/index.html", context)


def mudar_senha(request) -> HttpResponse:
    """Mudar a senha de uma conta."""
    # Pegando os parâmetros na query.
    id = request.GET.get("id", "")
    senha_antiga = request.GET.get("senha_antiga", "")
    senha_nova = request.GET.get("senha_nova", "")

    # Validando os parâmetros.
    erros = {"vazio":[], "400":False, "401":False}
    if id == "" or not id.isnumeric():
        erros["vazio"].append("id")
    if senha_antiga == "":
        erros["vazio"].append("senha_antiga")
    if senha_nova == "":
        erros["vazio"].append("senha_nova")

    # Fazendo um request na API para efetuar o login.
    if len(erros["vazio"]) == 0:
        response = conn.mudar_senha(int(id), senha_antiga, senha_nova)

        # Validando o resultado.
        if response.status_code == 200: # OK
            # Montando o HttpResponse. (MUDAR PARA PÁGINS DPS)
            return redirect("login:index")
        
        elif response.status_code == 400: # BadRequest
            erros["400"] = True
        
        elif response.status_code == 401: # Unauthorized
            erros["401"] = True

    # Renderizando a página html
    context = {
        "erros": erros
    }
    print(context)
    return render(request, "mudar_senha/index.html", context)


def refresh_token(request, id, senha):
    """Retorna um novo token para garantir que o usuário continue logado (caso o refresh_token seja válido)."""
    return HttpResponse("GET refrsh_token")


def sair(request):
    # Montando o HttpResponse. (MUDAR PARA PÁGINS DPS)
    expires = datetime.utcnow() + timedelta(days=7)
    return set_cookies(redirect("login:index"), api.Login())


def get_cargo_redirect(request_or_str, is_request: bool = False) -> HttpResponseRedirect:
    if is_request:
        cargo = request_or_str.COOKIES[os.environ['API_USER_CARGO']]
    else:
        cargo = request_or_str
    return redirect(f"{cargo.lower()}:index")


def is_logged(request: HttpRequest) -> [bool, api.Login]:
    """Verifique se um usuário está logado ou não.
    \nCaso esteja logado, retorna um HttpResponseRedirect para a sua respectiva área.
    \nCaso contrário, retorna None."""
    # Tentando instanciar um objeto do tipo Login.
    login = api.Login()
    try:
        login.token = request.COOKIES[os.environ['API_TOKEN']]
        login.refresh_token = request.COOKIES[os.environ['API_REFRESH_TOKEN']]
        login.cargo = request.COOKIES[os.environ['API_USER_CARGO']]
        login.id = int(request.COOKIES[os.environ['API_USER_ID']])
    except Exception as e:
        return False, login
    
    # Verificando o cargo do usuário em questão.
    if login.cargo == utils.Cargo.ANALISTARH:
        response, analistarh = conn.consultar.analistarh(login.token, login.id)
    elif login.cargo == utils.Cargo.SECRETARIO:
        response, secretario = conn.consultar.secretario(login.token, login.id)
    elif login.cargo == utils.Cargo.PROFESSOR:
        response, professor = conn.consultar.professor(login.token, login.id)
    elif login.cargo == utils.Cargo.ALUNO:
        response, aluno = conn.consultar.aluno(login.token, login.id)
    else:
        return False, login
    
    print(response.status_code)
    # Resultado da requisição.
    if response.status_code == 401:
        # Verificando se o refresh_token é válido
        refresh = conn.refresh(login.id, login.token, login.refresh_token)
        print(refresh.status_code)
        if refresh.status_code == 400:
            return False, login
    
    # Caso tenha passado por todas as validações.
    return True, login

def set_cookies(r: HttpResponse, login: api.Login) -> HttpResponse:
    expires = datetime.utcnow() + timedelta(days=7)
    r.set_cookie(os.environ["API_TOKEN"], login.token, expires=expires)
    r.set_cookie(os.environ["API_REFRESH_TOKEN"], login.refresh_token, expires=expires)
    r.set_cookie(os.environ["API_USER_CARGO"], login.cargo, expires=expires)
    r.set_cookie(os.environ["API_USER_ID"], login.id, expires=expires)
    return r

mysite/login/templates/secretario/index.html
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Área do Secretário</title>
    {% load static %}
    <link rel="shortcut icon" href="{% static 'icons/favicon.png'%}" type="image/x-icon">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/area.css'%}">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/area_header.css'%}">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/area_main.css'%}">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/area_footer.css'%}">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/area_do_analistarh.css'%}">
</head>
<body>
    <!-- Header, o cabeçalho da página -->
    <header>
        <!-- Ícone do sistema-->
        <div id="header-favicon">
            <img src="{% static 'icons/favicon.png'%}" alt="Íone da Universidade">
        </div>

        <!-- Título (h1) da página -->
        <div id="header-title">
            <h1>Área do Secretário</h1>
            <p>Olá, {{ secretario.nome }}!</p>
        </div>

        <!-- Botões do cabeçalho-->
        <div id="header-buttons">
            <!-- Botão sair (link para a rota no Back End) -->
            <div id="sair-button">
                <a href="{% url 'login:sair' %}">Sair</a>
            </div>
            
            <!-- Botão trocar de senha (link para a rota no Back End) -->
            <div id="trocar-de-senha-button">
                <a href="{% url 'login:mudar_senha_pag' %}">Trocar de Senha</a>
            </div>
        </div>

        <div class="clear"></div>
    </header>

    <!-- Main, onde fica todo o conteúdo principal da página -->
    <main>
        <section> <!-- Coloque o conteúdo dentro desta seção, pois ela é centralizada -->
            <div class="container"> 
                <div class="option-item">
                    <a href="{% url 'secretario:professor_em_turma'  %}">
                        <div class="option-item-icon">
                            <img src="{% static 'icons/manter_professor.png'%}" alt="">
                        </div>
                        <h2>Disciplinas Ministradas por Professores</h2>
                    </a>
                </div>
                <div class="option-item">
                    <a href="{% url 'secretario:aluno_em_curso'  %}">
                        <div class="option-item-icon">
                            <img src="{% static 'icons/manter_aluno.png'%}" alt="">
                        </div>
                        <h2>Alunos Matriculados em Cursos</h2>
                    </a>
                </div>
                <div class="option-item">
                    <a href="{% url 'secretario:disciplina_em_curso'  %}">
                        <div class="option-item-icon">
                            <img src="{% static 'icons/manter_disciplinaemcurso.png'%}" alt="">
                        </div>
                        <h2>Disciplinas em Cursos</h2>
                    </a>
                </div>
                <div class="option-item">
                    <a href="{% url 'secretario:aluno'  %}">
                        <div class="option-item-icon">
                            <img src="{% static 'icons/manter_alunocurso.png'%}" alt="">
                        </div>
                        <h2>Alunos</h2>
                    </a>
                </div>
                <div class="option-item">
                    <a href="{% url 'secretario:curso'  %}">
                        <div class="option-item-icon">
                            <img src="{% static 'icons/manter_curso.png'%}" alt="">
                        </div>
                        <h2>Cursos</h2>
                    </a>
                </div>
                <div class="option-item">
                    <a href="{% url 'secretario:turma'  %}">
                        <div class="option-item-icon">
                            <img src="{% static 'icons/manter_turma.png'%}" alt="">
                        </div>
                        <h2>Turmas</h2>
                    </a>
                </div>
                <div class="option-item">
                    <a href="{% url 'secretario:disciplina'  %}">
                        <div class="option-item-icon">
                            <img src="{% static 'icons/manter_disciplina.png'%}" alt="">
                        </div>
                        <h2>Disciplinas</h2>
                    </a>
                </div>
        </section>
    </main>

    <!-- Footer, o rodapé da página -->
    <footer>
        <!-- Primeira seção do rodapé -->
        <section id="footer-section-1">
            <h2>Sobre</h2>
            <p>PIM do 4° Semestre</p>
            <p>Grupo: DS4.4</p>
        </section>

        <!-- Segunda seção do rodapé -->
        <section id="footer-section-2">
            <h2>Atribuições</h2>
            <p><a href="https://www.flaticon.com/br/icones-gratis/universidade" class="link" target="_blank">Favicon by Flaticon</a></p>
            <p><a href="https://www.freepik.com" class="link" target="_blank">Icons by Freepik</a></p>
        </section>
    </footer>
</body>
</html>

mysite/login/templates/secretario/info_aluno_em_curso.html
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Área do Secretario</title>
    {% load static %}
    <link rel="shortcut icon" href="{% static 'icons/favicon.png'%}" type="image/x-icon">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/area.css'%}">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/area_header.css'%}">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/area_main.css'%}">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/area_footer.css'%}">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/info.css'%}">
    {% load static %}
    <script src="{% static 'js/manter.js' %}"></script>
</head>
<body>
    <!-- Header, o cabeçalho da página -->
    <header>
        <!-- Ícone do sistema-->
        <div id="header-favicon">
            <img src="{% static 'icons/favicon.png' %}" alt="Íone da Universidade">
        </div>

        <!-- Título (h1) da página -->
        <div id="header-title">
            <h1>
                <a href="{% url 'secretario:index'%}">Área do Secretario</a>
                <span class="subtitle"> / Curso Matriculado</span>
            </h1>
            <p>Olá, {{secretario.nome}}!</p>
        </div>

        <!-- Botões do cabeçalho-->
        <div id="header-buttons">
            <!-- Botão sair (link para a rota no Back End) -->
            <div id="sair-button">
                <a href="{% url 'login:sair' %}">Sair</a>
            </div>
            
            <!-- Botão trocar de senha (link para a rota no Back End) -->
            <div id="trocar-de-senha-button">
                <a href="{% url 'login:mudar_senha_pag' %}">Trocar de Senha</a>
            </div>
        </div>

        <div class="clear"></div>
    </header>

    <!-- Main, onde fica todo o conteúdo principal da página -->
    <main>
        <section> <!-- Coloque o conteúdo dentro desta seção, pois ela é centralizada -->
            <div class="container"> 
                <div id="retornos">
                    {% if status.200 %} <div class="block-success">Cadastro/Alteração realizado(a) com sucesso.</div> {% endif %}
                    {% if status.200_delete %} <div class="block-success">Cadastro apagado com sucesso.</div> {% endif %}
                    {% if status.delete_error %} <div class="block-erro">Erro ao apagar cadastro.</div> {% endif %}
                    {% if status.400 %} <div class="block-erro">Um ou mais dados inseridos são inválidos.</div> {% endif %}
                    {% if status.409 %} <div class="block-erro">Um ou mais dados já pertecem a outro cadastro.</div> {% endif %}
                    {% if status.418 %} <div class="block-erro">Este cadastro não pode ser deletado pois está relacionado à outros.</div> {% endif %}
                    {% if status.500 %} <div class="block-erro">Ocorreu um erro com o servidor.</div> {% endif %}
                </div>
                <form action="{% url 'secretario:aluno_em_curso_salvar'  %}" method="get">

                    <div>
                        {% if cadastro != None %}
                        <button type="button" onclick="redirect_to_cad(`{% url 'secretario:aluno_em_curso_apagar' %}`,
                        `{{ cadastro.id }}`)">
                            <img src="{% static 'icons/apagar.png' %}" alt="">
                            <span>Apagar</span>
                        </button>
                        <input type="text" name="id" id="id" value="{{ cadastro.id }}" style="display: none;">
                        {% endif %}
                        <button type="submit">
                            <img src="{% static 'icons/novo.png' %}" alt="">
                            <span>Salvar</span>
                        </button>
                        <div style="clear: both;"></div>
                    </div>
            
                    <div class="form-input">
                        <input class="input" type="number" name="id_aluno" id="id_aluno" placeholder="Insira o valor aqui" required
                        {% if cadastro != None %} value="{{ cadastro.aluno.id }}" {% endif %}>
                        <label for="id_aluno">ID do Aluno</label>
                    </div>
                    <div class="form-input">
                        <input class="input" type="number" name="id_curso" id="id_curso" placeholder="Insira o valor aqui" required
                        {% if cadastro != None %} value="{{ cadastro.curso.id }}" {% endif %}>
                        <label for="id_curso">ID do Curso</label>
                    </div>
            
                    <div class="form-input">
                        <input class="input" type="number" name="id_turma" id="id_turma" placeholder="Insira o valor aqui" required
                        {% if cadastro != None %} value="{{ cadastro.turma.id }}" {% endif %}>
                        <label for="id_turma">ID da Turma</label>
                    </div>

                    <!-- Opções de Input que só apareceram caso esteja editando um cadastro -->
                    {% if cadastro != None %}
                    <div class="form-input">
                        <input class="input" type="number" name="semestre_atual" id="semestre_atual" placeholder="Insira o valor aqui" required
                        {% if cadastro != None %} value="{{ cadastro.semestre_atual }}" {% endif %}>
                        <label for="semestre_atual">Semestre Atual</label>
                    </div>
                    <div class="form-input-select">
                        <input type="checkbox" name="trancado" id="trancado" {% if cadastro.trancado %} checked {% endif%}>
                        <label for="trancado">Trancado</label>
                        <div style="clear: both;"></div>
                    </div>
                    <div class="form-input-select">
                        <input type="checkbox" name="finalizado" id="finalizado" {% if cadastro.finalizado %} checked {% endif%}>
                        <label for="finalizado">Finalizado</label>
                        <div style="clear: both;"></div>
                    </div>
                    {% endif %}

                    <div style="clear: both;"></div>
                </form>
        </section>
    </main>

    <!-- Footer, o rodapé da página -->
    <footer>
        <!-- Primeira seção do rodapé -->
        <section id="footer-section-1">
            <h2>Sobre</h2>
            <p>PIM do 4° Semestre</p>
            <p>Grupo: DS4.4</p>
        </section>

        <!-- Segunda seção do rodapé -->
        <section id="footer-section-2">
            <h2>Atribuições</h2>
            <p><a href="https://www.flaticon.com/br/icones-gratis/universidade" class="link" target="_blank">Favicon by Flaticon</a></p>
            <p><a href="https://www.freepik.com" class="link" target="_blank">Icons by Freepik</a></p>
        </section>
    </footer>
</body>
</html>

mysite/login/templates/secretario/manter_disciplina_em_curso.html
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Área do Secretario</title>
    {% load static %}
    <link rel="shortcut icon" href="{% static 'icons/favicon.png'%}" type="image/x-icon">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/area.css'%}">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/area_header.css'%}">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/area_main.css'%}">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/area_footer.css'%}">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/manter.css'%}">
    {% load static %}
    <script src="{% static 'js/manter.js' %}"></script>
</head>
<body>
    <!-- Header, o cabeçalho da página -->
    <header>
        <!-- Ícone do sistema-->
        <div id="header-favicon">
            <img src="{% static 'icons/favicon.png' %}" alt="Íone da Universidade">
        </div>

        <!-- Título (h1) da página -->
        <div id="header-title">
            <h1>
                <a href="{% url 'secretario:index'%}">Área do Secretario</a>
                <span class="subtitle"> / Curso / Disciplinas</span>
            </h1>
            <p>Olá, {{secretario.nome}}!</p>
        </div>

        <!-- Botões do cabeçalho-->
        <div id="header-buttons">
            <!-- Botão sair (link para a rota no Back End) -->
            <div id="sair-button">
                <a href="{% url 'login:sair' %}">Sair</a>
            </div>
            
            <!-- Botão trocar de senha (link para a rota no Back End) -->
            <div id="trocar-de-senha-button">
                <a href="{% url 'login:mudar_senha_pag' %}">Trocar de Senha</a>
            </div>
        </div>

        <div class="clear"></div>
    </header>

    <!-- Main, onde fica todo o conteúdo principal da página -->
    <main>
        <section> <!-- Coloque o conteúdo dentro desta seção, pois ela é centralizada -->
            <div class="container">
                <div id="retornos">
                    {% if status.200 %} <div class="block-success">Cadastro/Alteração realizado(a) com sucesso.</div> {% endif %}
                    {% if status.200_delete %} <div class="block-success">Cadastro apagado com sucesso.</div> {% endif %}
                    {% if status.delete_error %} <div class="block-erro">Erro ao apagar cadastro.</div> {% endif %}
                    {% if status.418 %} <div class="block-erro">Este cadastro não pode ser deletado pois está relacionado à outros.</div> {% endif %}
                    {% if status.400 %} <div class="block-erro">Um ou mais dados inseridos são inválidos.</div> {% endif %}
                    {% if status.409 %} <div class="block-erro">Um ou mais dados já pertecem a outro cadastro.</div> {% endif %}
                    {% if status.500 %} <div class="block-erro">Ocorreu um erro com o servidor.</div> {% endif %}
                </div>
                <form action="{% url 'secretario:disciplina_em_curso' %}" method="get">
                    <input type="number" name="filtro" id="filtro" placeholder="Insira o ID do curso para pesquisar" required>
                    <button type="button" onclick="redirect_to_cad(`{% url 'secretario:disciplina_em_curso_info' %}`, null)">
                        <img src="{% static 'icons/manter_novo.png' %}" alt="">
                        <span>Novo</span>
                    </button>
                    <button type="submit">
                        <img src="{% static 'icons/lupa_pesquisa.png' %}" alt="">
                        <span>Pesquisar</span>
                    </button>
                    <!-- <input type="submit" value="Pesquisar">
                    <input type="button" value="Novo"> -->
                    <div style="clear: both;"></div>
                </form>
                <table>
                    <tr>
                        <th>Nome</th>
                        <th></th>
                    </tr>
                    {% for item in resultados %}
                    <tr class="table-row-non-clickabe">
                        <td>{{ item.nome }}</td>
                        <td class="doc_btn_download last-table-item" onclick="remover_disicplina(`{% url 'secretario:disciplina_em_curso_apagar' %}`, `{{ item.id }}`, `{{ item.id_curso }}`)">Remover</td>
                    </tr>
                    {% endfor %}
                </table>
        </section>
    </main>

    <!-- Footer, o rodapé da página -->
    <footer>
        <!-- Primeira seção do rodapé -->
        <section id="footer-section-1">
            <h2>Sobre</h2>
            <p>PIM do 4° Semestre</p>
            <p>Grupo: DS4.4</p>
        </section>

        <!-- Segunda seção do rodapé -->
        <section id="footer-section-2">
            <h2>Atribuições</h2>
            <p><a href="https://www.flaticon.com/br/icones-gratis/universidade" class="link" target="_blank">Favicon by Flaticon</a></p>
            <p><a href="https://www.freepik.com" class="link" target="_blank">Icons by Freepik</a></p>
        </section>
    </footer>
</body>
</html>